#!/usr/bin/env fish
# fish completion support for render

function __fish_render_using_command
  set -l cmds __render __render_version __render_commands __render_config __render_config_schema __render_config_init __render_regions __render_repo __render_repo_from_template __render_blueprint __render_blueprint_launch __render_buildpack __render_buildpack_init __render_buildpack_remove __render_buildpack_add __render_services __render_services_show __render_services_list __render_services_tail __render_services_ssh __render_deploys __render_deploys_list __render_jobs __render_jobs_list __render_custom_domains __render_custom_domains_list __render_completions __render_completions_bash __render_completions_fish __render_completions_zsh
  set -l words (commandline -opc)
  set -l cmd "_"
  for word in $words
    switch $word
      case '-*'
        continue
      case '*'
        set word (string replace -r -a '\W' '_' $word)
        set -l cmd_tmp $cmd"_$word"
        if contains $cmd_tmp $cmds
          set cmd $cmd_tmp
        end
    end
  end
  if test "$cmd" = "$argv[1]"
    return 0
  end
  return 1
end

complete -c render -n '__fish_render_using_command __render' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render' -s p -l profile -k -f -r -a '(render completions complete string )' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render' -s r -l region -k -f -r -a '(render completions complete string )' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render' -k -f -a version -d 'Shows the application version.'
complete -c render -n '__fish_render_using_command __render_version' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_version' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_version' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_version' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_version' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_version' -s p -l profile -k -f -r -a '(render completions complete string version)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_version' -s r -l region -k -f -r -a '(render completions complete string version)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render' -k -f -a commands -d 'Lists all commands and subcommands.'
complete -c render -n '__fish_render_using_command __render_commands' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_commands' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_commands' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_commands' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_commands' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_commands' -s p -l profile -k -f -r -a '(render completions complete string commands)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_commands' -s r -l region -k -f -r -a '(render completions complete string commands)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render' -k -f -a config -d 'Commands for interacting with the render-cli configuration.'
complete -c render -n '__fish_render_using_command __render_config' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_config' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_config' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_config' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_config' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_config' -s p -l profile -k -f -r -a '(render completions complete string config)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_config' -s r -l region -k -f -r -a '(render completions complete string config)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_config' -k -f -a schema -d 'Displays the render-cli config schema (YAML; JSON Schema format).'
complete -c render -n '__fish_render_using_command __render_config_schema' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_config_schema' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_config_schema' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_config_schema' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_config_schema' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_config_schema' -s p -l profile -k -f -r -a '(render completions complete string config schema)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_config_schema' -s r -l region -k -f -r -a '(render completions complete string config schema)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_config' -k -f -a init -d 'Interactively creates a Render CLI config file.'
complete -c render -n '__fish_render_using_command __render_config_init' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_config_init' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_config_init' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_config_init' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_config_init' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_config_init' -s p -l profile -k -f -r -a '(render completions complete string config init)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_config_init' -s r -l region -k -f -r -a '(render completions complete string config init)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_config_init' -s f -l force -k -f -d 'overwrites existing files if found.'
complete -c render -n '__fish_render_using_command __render' -k -f -a regions -d 'Lists the Render regions that this version of the CLI knows about.'
complete -c render -n '__fish_render_using_command __render_regions' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_regions' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_regions' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_regions' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_regions' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_regions' -s p -l profile -k -f -r -a '(render completions complete string regions)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_regions' -s r -l region -k -f -r -a '(render completions complete string regions)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render' -k -f -a repo -d 'Commands for managing Render projects/repos.'
complete -c render -n '__fish_render_using_command __render_repo' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_repo' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_repo' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_repo' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_repo' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_repo' -s p -l profile -k -f -r -a '(render completions complete string repo)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_repo' -s r -l region -k -f -r -a '(render completions complete string repo)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_repo' -k -f -a from-template -d 'Initializes a new project repository from a template.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -k -f -a '(render completions complete string repo from-template)'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s p -l profile -k -f -r -a '(render completions complete string repo from-template)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s r -l region -k -f -r -a '(render completions complete string repo from-template)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s o -l output-directory -k -f -r -a '(render completions complete string repo from-template)' -d 'target directory for new repo'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -s f -l force -k -f -d 'overwrites existing directory if found.'
complete -c render -n '__fish_render_using_command __render_repo_from_template' -l skip-cleanup -k -f -d 'skips cleaning up tmpdir (on success or failure)'
complete -c render -n '__fish_render_using_command __render' -k -f -a blueprint -d 'Commands for interacting with Render Blueprints (render.yaml files).'
complete -c render -n '__fish_render_using_command __render_blueprint' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_blueprint' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_blueprint' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_blueprint' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_blueprint' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_blueprint' -s p -l profile -k -f -r -a '(render completions complete string blueprint)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_blueprint' -s r -l region -k -f -r -a '(render completions complete string blueprint)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_blueprint' -k -f -a launch -d 'Opens the browser-based Render Deploy for the `origin` upstream for the repo (for the current working directory) or a remote repo that you've specified.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -k -f -a '(render completions complete string blueprint launch)'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s p -l profile -k -f -r -a '(render completions complete string blueprint launch)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s r -l region -k -f -r -a '(render completions complete string blueprint launch)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s l -l link -k -f -d 'Prints out the Render Deploy URL rather than attempting to open it.'
complete -c render -n '__fish_render_using_command __render_blueprint_launch' -s r -l remote -k -f -r -a '(render completions complete string blueprint launch)' -d 'The remote to use'
complete -c render -n '__fish_render_using_command __render' -k -f -a buildpack -d 'Commands for using buildpacks in Render'
complete -c render -n '__fish_render_using_command __render_buildpack' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_buildpack' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_buildpack' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_buildpack' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_buildpack' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_buildpack' -s p -l profile -k -f -r -a '(render completions complete string buildpack)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_buildpack' -s r -l region -k -f -r -a '(render completions complete string buildpack)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_buildpack' -k -f -a init -d 'Initializes a repository for use with Heroku-style buildpacks within Render.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -k -f -a '(render completions complete string buildpack init)'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -s p -l profile -k -f -r -a '(render completions complete string buildpack init)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -s r -l region -k -f -r -a '(render completions complete string buildpack init)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -s f -l force -k -f -d 'overwrites existing files if found.'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -l dir -k -f -r -a '(render completions complete string buildpack init)' -d 'the directory in which to run this command'
complete -c render -n '__fish_render_using_command __render_buildpack_init' -l skip-dockerfile -k -f -d 'don't emit a Dockerfile'
complete -c render -n '__fish_render_using_command __render_buildpack' -k -f -a remove -d 'Removes buildpacks from your .render-buildpacks.json file.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -k -f -a '(render completions complete string buildpack remove)'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -s p -l profile -k -f -r -a '(render completions complete string buildpack remove)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -s r -l region -k -f -r -a '(render completions complete string buildpack remove)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_buildpack_remove' -l dir -k -f -r -a '(render completions complete string buildpack remove)' -d 'the directory in which to run this command'
complete -c render -n '__fish_render_using_command __render_buildpack' -k -f -a add -d 'Adds buildpacks to your .render-buildpacks.json file.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -k -f -a '(render completions complete string buildpack add)'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -s p -l profile -k -f -r -a '(render completions complete string buildpack add)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -s r -l region -k -f -r -a '(render completions complete string buildpack add)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_buildpack_add' -l dir -k -f -r -a '(render completions complete string buildpack add)' -d 'the directory in which to run this command'
complete -c render -n '__fish_render_using_command __render' -k -f -a services -d 'Commands for observing and managing Render services.'
complete -c render -n '__fish_render_using_command __render_services' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_services' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_services' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_services' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_services' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_services' -s p -l profile -k -f -r -a '(render completions complete string services)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_services' -s r -l region -k -f -r -a '(render completions complete string services)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_services' -k -f -a show -d 'Fetches full details about a single service.'
complete -c render -n '__fish_render_using_command __render_services_show' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_services_show' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_services_show' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_services_show' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_services_show' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_services_show' -s p -l profile -k -f -r -a '(render completions complete string services show)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_services_show' -s r -l region -k -f -r -a '(render completions complete string services show)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_services_show' -l id -k -f -r -a '(render completions complete string services show)' -d 'the service ID (e.g. `srv-12345`)'
complete -c render -n '__fish_render_using_command __render_services' -k -f -a list -d 'Lists the services this user can see.'
complete -c render -n '__fish_render_using_command __render_services_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_services_list' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_services_list' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_services_list' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_services_list' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_services_list' -s p -l profile -k -f -r -a '(render completions complete string services list)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_services_list' -s r -l region -k -f -r -a '(render completions complete string services list)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_services_list' -l format -k -f -r -a '(render completions complete string services list)' -d 'interactive output format'
complete -c render -n '__fish_render_using_command __render_services_list' -l columns -k -f -r -a '(render completions complete string services list)' -d 'if --format table, the columns to show.'
complete -c render -n '__fish_render_using_command __render_services_list' -l name -k -f -r -a '(render completions complete string services list)' -d 'the name of a service to filter by'
complete -c render -n '__fish_render_using_command __render_services_list' -l type -k -f -r -a '(render completions complete string services list)' -d 'the service type to filter by'
complete -c render -n '__fish_render_using_command __render_services_list' -l env -k -f -r -a '(render completions complete string services list)' -d 'the runtime environment (docker, ruby, python, etc.)'
complete -c render -n '__fish_render_using_command __render_services_list' -l service-region -k -f -r -a '(render completions complete string services list)' -d 'the region in which a service is located'
complete -c render -n '__fish_render_using_command __render_services_list' -l ownerid -k -f -r -a '(render completions complete string services list)' -d 'the owner ID for the service'
complete -c render -n '__fish_render_using_command __render_services_list' -l created-before -k -f -r -a '(render completions complete string services list)' -d 'services created before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_services_list' -l created-after -k -f -r -a '(render completions complete string services list)' -d 'services created after (ISO8601)'
complete -c render -n '__fish_render_using_command __render_services_list' -l updated-before -k -f -r -a '(render completions complete string services list)' -d 'services updated before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_services_list' -l updated-after -k -f -r -a '(render completions complete string services list)' -d 'services updated after (ISO8601)'
complete -c render -n '__fish_render_using_command __render_services' -k -f -a tail -d 'Tails logs for a given service.'
complete -c render -n '__fish_render_using_command __render_services_tail' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_services_tail' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_services_tail' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_services_tail' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_services_tail' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_services_tail' -s p -l profile -k -f -r -a '(render completions complete string services tail)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_services_tail' -s r -l region -k -f -r -a '(render completions complete string services tail)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_services_tail' -l raw -k -f -d 'only prints the bare text of the log to stdout'
complete -c render -n '__fish_render_using_command __render_services_tail' -l json -k -f -d 'prints Render's log tail as JSON, one per message'
complete -c render -n '__fish_render_using_command __render_services_tail' -l deploy-id -k -f -r -a '(render completions complete string services tail)' -d 'filter logs to the requested deploy ID'
complete -c render -n '__fish_render_using_command __render_services_tail' -l id -k -f -r -a '(render completions complete string services tail)' -d 'the service ID whose logs to request'
complete -c render -n '__fish_render_using_command __render_services' -k -f -a ssh -d 'Opens a SSH session to a Render service.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -k -f -a '(render completions complete string services ssh)'
complete -c render -n '__fish_render_using_command __render_services_ssh' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -s p -l profile -k -f -r -a '(render completions complete string services ssh)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -s r -l region -k -f -r -a '(render completions complete string services ssh)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -l preserve-hosts -k -f -d 'Do not update ~/.ssh/known_hosts with Render public keys.'
complete -c render -n '__fish_render_using_command __render_services_ssh' -l id -k -f -r -a '(render completions complete string services ssh)' -d 'The service ID to access via SSH.'
complete -c render -n '__fish_render_using_command __render' -k -f -a deploys -d 'Commands for observing and managing deploys of Render services.'
complete -c render -n '__fish_render_using_command __render_deploys' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_deploys' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_deploys' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_deploys' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_deploys' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_deploys' -s p -l profile -k -f -r -a '(render completions complete string deploys)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_deploys' -s r -l region -k -f -r -a '(render completions complete string deploys)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_deploys' -k -f -a list -d 'Lists the deploys for a given service.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -s p -l profile -k -f -r -a '(render completions complete string deploys list)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -s r -l region -k -f -r -a '(render completions complete string deploys list)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l format -k -f -r -a '(render completions complete string deploys list)' -d 'interactive output format'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l columns -k -f -r -a '(render completions complete string deploys list)' -d 'if --format table, the columns to show.'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l service-id -k -f -r -a '(render completions complete string deploys list)' -d 'the service whose deploys to retrieve'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l start-time -k -f -r -a '(render completions complete number deploys list)' -d 'start of the time range to return'
complete -c render -n '__fish_render_using_command __render_deploys_list' -l end-time -k -f -r -a '(render completions complete number deploys list)' -d 'end of the time range to return'
complete -c render -n '__fish_render_using_command __render' -k -f -a jobs -d 'Commands for observing and managing Render jobs.'
complete -c render -n '__fish_render_using_command __render_jobs' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_jobs' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_jobs' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_jobs' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_jobs' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_jobs' -s p -l profile -k -f -r -a '(render completions complete string jobs)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_jobs' -s r -l region -k -f -r -a '(render completions complete string jobs)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_jobs' -k -f -a list -d 'Lists the jobs this user can see.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -s p -l profile -k -f -r -a '(render completions complete string jobs list)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -s r -l region -k -f -r -a '(render completions complete string jobs list)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l format -k -f -r -a '(render completions complete string jobs list)' -d 'interactive output format'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l columns -k -f -r -a '(render completions complete string jobs list)' -d 'if --format table, the columns to show.'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l service-id -k -f -r -a '(render completions complete string jobs list)' -d 'the service whose deploys to retrieve'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l status -k -f -r -a '(render completions complete string jobs list)' -d ''pending', 'running', 'succeeded', or 'failed''
complete -c render -n '__fish_render_using_command __render_jobs_list' -l created-before -k -f -r -a '(render completions complete string jobs list)' -d 'jobs created before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l created-after -k -f -r -a '(render completions complete string jobs list)' -d 'jobs created after (ISO8601)'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l started-before -k -f -r -a '(render completions complete string jobs list)' -d 'jobs started before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l started-after -k -f -r -a '(render completions complete string jobs list)' -d 'jobs started after (ISO8601)'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l finished-before -k -f -r -a '(render completions complete string jobs list)' -d 'jobs finished before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_jobs_list' -l finished-after -k -f -r -a '(render completions complete string jobs list)' -d 'jobs finished after (ISO8601)'
complete -c render -n '__fish_render_using_command __render' -k -f -a custom-domains -d 'Commands for observing and managing custom domains.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -s p -l profile -k -f -r -a '(render completions complete string custom-domains)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -s r -l region -k -f -r -a '(render completions complete string custom-domains)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_custom_domains' -k -f -a list -d 'Lists the custom domains for a given service.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -s v -l verbose -k -f -d 'Makes render-cli a lot more chatty.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l non-interactive -k -f -d 'Forces Render to act as though it's not in a TTY.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l pretty-json -k -f -d 'If in non-interactive mode, prints prettified JSON.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l json-record-per-line -k -f -d 'if emitting JSON, prints each JSON record as a separate line of stdout.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -s p -l profile -k -f -r -a '(render completions complete string custom-domains list)' -d 'The Render profile to use for this invocation. Overrides RENDERCLI_PROFILE.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -s r -l region -k -f -r -a '(render completions complete string custom-domains list)' -d 'The Render region to use for this invocation; always accepted but not always relevant. Overrides RENDERCLI_REGION.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l format -k -f -r -a '(render completions complete string custom-domains list)' -d 'interactive output format'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l columns -k -f -r -a '(render completions complete string custom-domains list)' -d 'if --format table, the columns to show.'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l service-id -k -f -r -a '(render completions complete string custom-domains list)' -d 'the service whose deploys to retrieve'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l name -k -f -r -a '(render completions complete string custom-domains list)' -d 'domain names to filter by'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l domain-type -k -f -r -a '(render completions complete string custom-domains list)' -d ''apex' or 'subdomain''
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l verification-status -k -f -r -a '(render completions complete string custom-domains list)' -d ''verified' or 'unverified''
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l created-before -k -f -r -a '(render completions complete string custom-domains list)' -d 'services created before (ISO8601)'
complete -c render -n '__fish_render_using_command __render_custom_domains_list' -l created-after -k -f -r -a '(render completions complete string custom-domains list)' -d 'services created after (ISO8601)'
complete -c render -n '__fish_render_using_command __render' -k -f -a completions -d 'Generate shell completions.'
complete -c render -n '__fish_render_using_command __render_completions' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_completions' -k -f -a bash -d 'Generate shell completions for bash.'
complete -c render -n '__fish_render_using_command __render_completions_bash' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_completions' -k -f -a fish -d 'Generate shell completions for fish.'
complete -c render -n '__fish_render_using_command __render_completions_fish' -s h -l help -x -k -f -d 'Show this help.'
complete -c render -n '__fish_render_using_command __render_completions' -k -f -a zsh -d 'Generate shell completions for zsh.'
complete -c render -n '__fish_render_using_command __render_completions_zsh' -s h -l help -x -k -f -d 'Show this help.'
